# -*- coding: utf-8 -*-
"""Flask-dio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6Qe0FKprxBOZuQSwHzOGyrKVCEERFI-
"""

!pip install pyngrok -q

!ngrok config add-authtoken [YOUR TOKEN HERE]

from flask import Flask, render_template, request
from pyngrok import ngrok
import pandas as pd

data = [
    {
        "Number": 1,
        "Name": "Mahesh",
        "Age": 25,
        "City": "Bangalore",
        "Country": "India"
    },
    {
        "Number": 2,
        "Name": "Alex",
        "Age": 26,
        "City": "London",
        "Country": "UK"
    },
    {
        "Number": 3,
        "Name": "David",
        "Age": 27,
        "City": "San Francisco",
        "Country": "USA"
    },
    {
        "Number": 4,
        "Name": "Jonh",
        "Age": 28,
        "City": "Toronto",
        "Country": "Canada"
    },
    {
        "Number": 5,
        "Name": "Chris",
        "Age": 29,
        "City": "Paris",
        "Country": "France"
    }
]

df = pd.DataFrame(data)
df

from tabulate import tabulate

#print(tabulate(df, tablefmt='html'))

@app.route('/')
def index(dataframe):
  return render_template('index.html', tabulate(dataframe, tablefmt='html'))

if __name__ == '__main__':
  ngrok_tunnel = ngrok.connect(5000)
  print('Public URL:', ngrok_tunnel.public_url)
  app.run()
